/*
 * ADC.c
 *
 *  Created on: Sep 24, 2022
 *      Author: mh_sm
 */

#include "../../../INCLUDE/MCAL/ADC/ADC.h"
#include "../../../INCLUDE/MCAL/ADC/ADC_cfg.h"
#include "../../../INCLUDE/MCAL/ADC/ADC_priv.h"
#include "../../../SERVICES/bit_utilies.h"
#include "../../../SERVICES/std_types.h"

void ADC_voidInit(){
	// VREF
#if ADC_VREF==ADC_VREF_AVCC_5V
	SET_BIT(ADCMUX_Register,ADC_VREF_ADMUX_REFS0);
	CLR_BIT(ADCMUX_Register,ADC_VREF_ADMUX_REFS1);
#elif ADC_VREF==ADC_VREF_AVCC_2V
	SET_BIT(ADCMUX_Register,ADC_VREF_ADMUX_REFS0);
	SET_BIT(ADCMUX_Register,ADC_VREF_ADMUX_REFS1);
#elif ADC_VREF==ADC_VREF_AREF
	CLR_BIT(ADCMUX_Register,ADC_VREF_ADMUX_REFS0);
	CLR_BIT(ADCMUX_Register,ADC_VREF_ADMUX_REFS1);
#elif ADC_VREF==ADC_VREF_RESERVED
	CLR_BIT(ADCMUX_Register,ADC_VREF_ADMUX_REFS0);
	SET_BIT(ADCMUX_Register,ADC_VREF_ADMUX_REFS1);
#else
	#warning INVALID VREF
#endif
	// AADJUSTMENT
#if ADC_ADJUSTMENT==ADC_ADJUSTMENT_RIGHT
	CLR_BIT(ADCMUX_Register,ADC_ADJUSTMENT_ADMUX_ADLAR);
#elif ADC_ADJUSTMENT==ADC_ADJUSTMENT_LEFT
	SET_BIT(ADCMUX_Register,ADC_ADJUSTMENT_ADMUX_ADLAR);
#else
	#warning INVALID ADJUSTMENT
#endif
	//PRESCALER
#if   ADC_PRESCALER==ADC_PRESCALER_128
	   SET_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS0);
	   SET_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS1);
	   SET_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS2);
#elif ADC_PRESCALER==ADC_PRESCALER_2
	   CLR_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS0);
	   CLR_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS1);
	   CLR_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS2);
#elif ADC_PRESCALER==ADC_PRESCALER_4
	   CLR_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS0);
	   SET_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS1);
	   CLR_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS2);
#elif ADC_PRESCALER==ADC_PRESCALER_8
	   SET_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS0);
	   SET_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS1);
	   CLR_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS2);
#elif ADC_PRESCALER==ADC_PRESCALER_16
	   CLR_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS0);
	   CLR_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS1);
	   SET_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS2);
#elif ADC_PRESCALER==ADC_PRESCALER_32
	   SET_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS0);
	   CLR_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS1);
	   SET_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS2);
#elif ADC_PRESCALER==ADC_PRESCALER_64
	   CLR_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS0);
	   SET_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS1);
	   SET_BIT(ADCSRA_Register,ADC_PRESCALER_ADCSRA_ADPS2);
#else
#warning INVALID PRESCALER
#endif
	   // ADC Analog Channel
#if ADC_ANALOG_CHANNEL==ADC_ANALOG_CHANNEL_PIN0
	   ADCSRA_Register&=0xE0;
#elif ADC_ANALOG_CHANNEL==ADC_ANALOG_CHANNEL_PIN1
	   ADCSRA_Register&=0xE1;
#elif ADC_ANALOG_CHANNEL==ADC_ANALOG_CHANNEL_PIN2
	   ADCSRA_Register&=0xE2;
#elif ADC_ANALOG_CHANNEL==ADC_ANALOG_CHANNEL_PIN3
	   ADCSRA_Register&=0xE3;
#elif ADC_ANALOG_CHANNEL==ADC_ANALOG_CHANNEL_PIN4
	   ADCSRA_Register&=0xE4;
#elif ADC_ANALOG_CHANNEL==ADC_ANALOG_CHANNEL_PIN5
	   ADCSRA_Register&=0xE5;
#elif ADC_ANALOG_CHANNEL==ADC_ANALOG_CHANNEL_PIN6
	   ADCSRA_Register&=0xE6;
#elif ADC_ANALOG_CHANNEL==ADC_ANALOG_CHANNEL_PIN7
	   ADCSRA_Register&=0xE7;
#else
		#warning INVALID ANALOG CHANNEL
#endif
}
void ADC_voidGetRead(u16*Add_u16AdcRead){
	//ENABLE
	SET_BIT(ADCSRA_Register,ADC_ENABLE_ADCSRA_ADEN);
	// Star Conversion
	SET_BIT(ADCSRA_Register,ADC_START_CONVERSION);
	u8 Loc_u8AdcTimeOutCounter=200;
	while(GET_BIT(ADCSRA_Register,ADC_START_CONVERSION)==ADC_CONVERSION_IN_PROGRESS && Loc_u8AdcTimeOutCounter>0){
		Loc_u8AdcTimeOutCounter--;
	}
	if(Loc_u8AdcTimeOutCounter==ADC_TimeOut){
		#warning ADC TIME OUT
	}
	else
		*Add_u16AdcRead=ADC_Register;
}
void ADC_voidDisable(){
	CLR_BIT(ADCSRA_Register,ADC_ENABLE_ADCSRA_ADEN);
}


